Repository kuzzleio/kourou, pull requests merged in 2020-06, with the labels that each got.

#43 Add realtime subscription support
  README.md
  features/Subscribe.feature
  features/step_definitions/cli-steps.js
  src/commands/collection/create.ts
  src/commands/document/create.ts
  src/commands/sdk/execute.ts
  src/commands/sdk/query.ts
  src/commands/subscribe.ts
  src/common.ts
  src/support/kuzzle.ts
Labels: changelog:new-features

#47 Fix sdk:execute from stdin
  src/commands/sdk/execute.ts
Labels: changelog:bug-fixes

#50 Allows to add credentials user export
  .vscode/settings.json
  README.md
  features/Import.feature
  features/User.feature
  package-lock.json
  package.json
  src/commands/collection/export.ts
  src/commands/collection/import.ts
  src/commands/config/diff.ts
  src/commands/file/decrypt.ts
  src/commands/file/encrypt.ts
  src/commands/file/test.ts
  src/commands/import.ts
  src/commands/index/export.ts
  src/commands/index/import.ts
  src/commands/instance/logs.ts
  src/commands/profile/export.ts
  src/commands/profile/import.ts
  src/commands/role/export.ts
  src/commands/role/import.ts
  src/commands/sdk/query.ts
  src/commands/subscribe.ts
  src/commands/user/export.ts
  src/commands/user/import.ts
  src/commands/vault/add.ts
  src/commands/vault/decrypt.ts
  src/commands/vault/encrypt.ts
  src/commands/vault/show.ts
  src/commands/vault/test.ts
  src/support/dump-collection.ts
  src/support/restore-collection.ts
  src/support/restore-securities.ts
Labels: changelog:enhancement

#52 Release 0.13.1
  .vscode/settings.json
  README.md
  features/Import.feature
  features/User.feature
  package-lock.json
  package.json
  src/commands/collection/export.ts
  src/commands/collection/import.ts
  src/commands/config/diff.ts
  src/commands/file/decrypt.ts
  src/commands/file/encrypt.ts
  src/commands/file/test.ts
  src/commands/import.ts
  src/commands/index/export.ts
  src/commands/index/import.ts
  src/commands/instance/logs.ts
  src/commands/profile/export.ts
  src/commands/profile/import.ts
  src/commands/role/export.ts
  src/commands/role/import.ts
  src/commands/sdk/execute.ts
  src/commands/sdk/query.ts
  src/commands/subscribe.ts
  src/commands/user/export.ts
  src/commands/user/import.ts
  src/commands/vault/add.ts
  src/commands/vault/decrypt.ts
  src/commands/vault/encrypt.ts
  src/commands/vault/show.ts
  src/commands/vault/test.ts
  src/support/dump-collection.ts
  src/support/restore-collection.ts
  src/support/restore-securities.ts
Labels: release

#51 [fix] readme links should be relative
  README.md
  package.json
Labels: changelog:exclude

#53 Add query hook for any API method
  README.md
  features/ApiMethodHook.feature
  features/Collection.feature
  features/Document.feature
  features/support/hooks.js
  package.json
  src/commands/collection/create.ts
  src/commands/document/create.ts
  src/commands/document/get.ts
  src/commands/sdk/query.ts
  src/hooks/command_not_found/api-method.ts
Labels: changelog:new-features
