Repository kuzzleio/kourou, pull requests merged in 2020-03, with the labels that each got.

#10 Add document create
  README.md
  features/ApiKey.feature
  features/Document.feature
  features/Query.feature
  features/Vault.feature
  features/step_definitions/cli-steps.js
  package-lock.json
  package.json
  src/commands/api-key/create.ts
  src/commands/api-key/delete.ts
  src/commands/api-key/search.ts
  src/commands/collection/dump.ts
  src/commands/collection/restore.ts
  src/commands/document/create.ts
  src/commands/document/get.ts
  src/commands/index/dump.ts
  src/commands/index/restore.ts
  src/commands/query.ts
  src/common.ts
  src/support/kuzzle.ts
  src/support/restore-collection.ts
Labels: enhancement

#11 Dump & restore roles or profiles
  README.md
  features/Profile.feature
  features/Role.feature
  features/step_definitions/common/security-steps.js
  src/commands/document/create.ts
  src/commands/profile/dump.ts
  src/commands/profile/restore.ts
  src/commands/role/dump.ts
  src/commands/role/restore.ts
  src/support/kuzzle.ts
Labels: enhancement

#12 Help messages per topics
  package.json
Labels: enhancement

#13 Add a shorthand for the --arg argument of the query command
  features/Query.feature
  src/commands/query.ts
Labels: enhancement

#14 Query: prints the full error object for better understanding
  src/commands/query.ts
Labels: enhancement

#15 Allow read from stdin for query and document:create
  .travis.yml
  README.md
  features/docker/docker-compose.yml
  features/step_definitions/common/documents-steps.js
  src/commands/document/create.ts
  src/commands/query.ts
  src/common.ts
Labels: changelog:enhancement

#16 Release 0.8.0
  .travis.yml
  README.md
  features/ApiKey.feature
  features/Document.feature
  features/Profile.feature
  features/Query.feature
  features/Role.feature
  features/Vault.feature
  features/docker/docker-compose.yml
  features/step_definitions/cli-steps.js
  features/step_definitions/common/documents-steps.js
  features/step_definitions/common/security-steps.js
  package-lock.json
  package.json
  src/commands/api-key/create.ts
  src/commands/api-key/delete.ts
  src/commands/api-key/search.ts
  src/commands/collection/dump.ts
  src/commands/collection/restore.ts
  src/commands/document/create.ts
  src/commands/document/get.ts
  src/commands/index/dump.ts
  src/commands/index/restore.ts
  src/commands/instance/spawn.ts
  src/commands/profile/dump.ts
  src/commands/profile/restore.ts
  src/commands/query.ts
  src/commands/role/dump.ts
  src/commands/role/restore.ts
  src/common.ts
  src/support/kuzzle.ts
  src/support/restore-collection.ts
Labels: release

#18 Adds more login time to allow dumping large collections
  src/commands/collection/dump.ts
  src/support/kuzzle.ts
Labels: changelog:enhancement

#17 Add vault:test
  README.md
  features/Vault.feature
  src/commands/collection/dump.ts
  src/commands/collection/restore.ts
  src/commands/index/dump.ts
  src/commands/index/restore.ts
  src/commands/vault/test.ts
  src/support/kuzzle.ts
Labels: changelog:new-features

#19 Fix index restore display bug
  src/support/restore-collection.ts
Labels: changelog:bug-fixes

#20 Release 0.9.0
  README.md
  features/Vault.feature
  package-lock.json
  package.json
  src/commands/collection/dump.ts
  src/commands/collection/restore.ts
  src/commands/index/dump.ts
  src/commands/index/restore.ts
  src/commands/vault/test.ts
  src/support/kuzzle.ts
  src/support/restore-collection.ts
Labels: release

#22 Make vault:test exit with code 1 in case of failure
  src/commands/vault/test.ts
Labels: changelog:bug-fixes

#23 Rename dump/restore to export/import
  README.md
  features/Collection.feature
  features/Index.feature
  features/Profile.feature
  features/Role.feature
  src/commands/collection/export.ts
  src/commands/collection/import.ts
  src/commands/index/export.ts
  src/commands/index/import.ts
  src/commands/profile/export.ts
  src/commands/profile/import.ts
  src/commands/role/export.ts
  src/commands/role/import.ts
  src/common.ts
Labels: changelog:breaking-changes

#21 Adds document:search
  README.md
  features/Document.feature
  features/step_definitions/cli-steps.js
  features/support/hooks.js
  package-lock.json
  package.json
  src/commands/document/create.ts
  src/commands/document/search.ts
  src/commands/query.ts
  src/common.ts
  src/support/editor.ts
Labels: changelog:new-features

#24 Fix login timeout on dump/restore
  features/Elasticsearch.feature
  src/commands/api-key/create.ts
  src/commands/api-key/delete.ts
  src/commands/api-key/search.ts
  src/commands/collection/export.ts
  src/commands/collection/import.ts
  src/commands/document/create.ts
  src/commands/document/get.ts
  src/commands/es/get.ts
  src/commands/es/insert.ts
  src/commands/es/list-index.ts
  src/commands/index/export.ts
  src/commands/index/import.ts
  src/commands/instance/logs.ts
  src/commands/instance/spawn.ts
  src/commands/profile/export.ts
  src/commands/profile/import.ts
  src/commands/query.ts
  src/commands/role/export.ts
  src/commands/role/import.ts
  src/commands/vault/add.ts
  src/commands/vault/encrypt.ts
  src/commands/vault/show.ts
  src/commands/vault/test.ts
  src/common.ts
  src/support/dump-collection.ts
  src/support/kuzzle.ts
Labels: changelog:bug-fixes

#25 Fix api-key:delete params
  README.md
  features/ApiKey.feature
  src/commands/api-key/delete.ts
  src/commands/profile/export.ts
  src/commands/role/export.ts
Labels: changelog:enhancement

#26 Allows to export only certain document from a collection
  README.md
  features/Collection.feature
  src/commands/collection/export.ts
  src/support/dump-collection.ts
Labels: changelog:enhancement

#27 Release 0.10.0
  README.md
  features/ApiKey.feature
  features/Collection.feature
  features/Document.feature
  features/Elasticsearch.feature
  features/Index.feature
  features/Profile.feature
  features/Role.feature
  features/step_definitions/cli-steps.js
  features/support/hooks.js
  package-lock.json
  package.json
  src/commands/api-key/create.ts
  src/commands/api-key/delete.ts
  src/commands/api-key/search.ts
  src/commands/collection/dump.ts
  src/commands/collection/export.ts
  src/commands/collection/import.ts
  src/commands/document/create.ts
  src/commands/document/get.ts
  src/commands/document/search.ts
  src/commands/es/get.ts
  src/commands/es/insert.ts
  src/commands/es/list-index.ts
  src/commands/index/export.ts
  src/commands/index/import.ts
  src/commands/instance/logs.ts
  src/commands/instance/spawn.ts
  src/commands/profile/export.ts
  src/commands/profile/import.ts
  src/commands/query.ts
  src/commands/role/export.ts
  src/commands/role/import.ts
  src/commands/vault/add.ts
  src/commands/vault/encrypt.ts
  src/commands/vault/show.ts
  src/commands/vault/test.ts
  src/common.ts
  src/support/dump-collection.ts
  src/support/editor.ts
  src/support/kuzzle.ts
Labels: release
