Repository kuzzleio/kourou, pull requests merged in 2020-10, with the labels that each got.

#63 Add api-key support
  README.md
  features/ApiKey.feature
  features/docker/docker-compose.yml
  features/run-kuzzle-stack.sh
  features/step_definitions/cli-steps.js
  src/support/execute.ts
  src/support/kuzzle.ts
Labels: changelog:new-features

#61 Add app:start-services command
  README.md
  package.json
  src/commands/app/scaffold.ts
  src/commands/app/start-services.ts
  src/commands/sdk/query.ts
  src/templates/app-scaffold/ts/features/.keep
  src/templates/app-scaffold/ts/test/.keep
  test/commands/app/start-services.test.ts
  test/commands/instance/kill.test.ts
  test/commands/instance/list.test.ts
  test/commands/instance/spawn.test.ts
Labels: changelog:new-features

#67 Fix document:search command
  README.md
  features/Document.feature
  features/RealtimeSubscribe.feature
  features/step_definitions/cli-steps.js
  src/commands/api-key/check.ts
  src/commands/api-key/create.ts
  src/commands/api-key/delete.ts
  src/commands/api-key/search.ts
  src/commands/collection/create.ts
  src/commands/collection/export.ts
  src/commands/document/search.ts
  src/commands/import.ts
  src/commands/index/export.ts
  src/commands/profile/export.ts
  src/commands/realtime/subscribe.ts
  src/commands/role/export.ts
  src/commands/sdk/execute.ts
  src/commands/sdk/query.ts
  src/commands/user/export-mappings.ts
  src/commands/user/export.ts
  src/commands/user/import-mappings.ts
  src/common.ts
  src/support/kuzzle.ts
  src/templates/app-scaffold/ts/tsconfig.json
Labels: changelog:enhancement

#68 Release 0.15.0
  .eslintignore
  .travis.yml
  README.md
  features/ApiKey.feature
  features/Document.feature
  features/InstanceLogs.feature
  features/QueryHook.feature
  features/RealtimeSubscribe.feature
  features/docker/docker-compose.yml
  features/docker/run.sh
  features/run-kuzzle-stack.sh
  features/step_definitions/cli-steps.js
  package-lock.json
  package.json
  src/commands/api-key/check.ts
  src/commands/api-key/create.ts
  src/commands/api-key/delete.ts
  src/commands/api-key/search.ts
  src/commands/app/scaffold.ts
  src/commands/app/start-services.ts
  src/commands/collection/create.ts
  src/commands/collection/export.ts
  src/commands/document/search.ts
  src/commands/import.ts
  src/commands/index/export.ts
  src/commands/instance/kill.ts
  src/commands/instance/list.ts
  src/commands/instance/logs.ts
  src/commands/instance/spawn.ts
  src/commands/profile/export.ts
  src/commands/realtime/subscribe.ts
  src/commands/role/export.ts
  src/commands/sdk/execute.ts
  src/commands/sdk/query.ts
  src/commands/user/export-mappings.ts
  src/commands/user/export.ts
  src/commands/user/import-mappings.ts
  src/common.ts
  src/hooks/command_not_found/api-method.ts
  src/support/dump-collection.ts
  src/support/execute.ts
  src/support/kuzzle.ts
  src/templates/app-scaffold/ts/.eslintignore
  src/templates/app-scaffold/ts/.eslintrc.json
  src/templates/app-scaffold/ts/.gitignore
  src/templates/app-scaffold/ts/.kuzzlerc
  src/templates/app-scaffold/ts/.mocharc.json
  src/templates/app-scaffold/ts/README.md
  src/templates/app-scaffold/ts/app.ts
  src/templates/app-scaffold/ts/lib/.keep
  src/templates/app-scaffold/ts/package.json
  src/templates/app-scaffold/ts/tsconfig.json
  test/commands/app/scaffold.test.ts
  test/commands/app/start-services.test.ts
  test/commands/instance/kill.test.ts
  test/commands/instance/list.test.ts
  test/commands/instance/spawn.test.ts
  tsconfig.json
Labels: release

#69 Fix app:start-services
  README.md
  package-lock.json
  package.json
  src/commands/app/start-services.ts
Labels: changelog:bug-fixes

#73 Add missing templates app:scaffold
  .travis.yml
  README.md
  features/Collection.feature
  features/Import.feature
  features/Index.feature
  features/step_definitions/cli-steps.js
  package.json
  src/commands/app/scaffold.ts
  src/hooks/command_not_found/api-method.ts
  src/support/kuzzle.ts
  templates/app-scaffold/ts/.eslintignore
  templates/app-scaffold/ts/.eslintrc.json
  templates/app-scaffold/ts/.gitignore
  templates/app-scaffold/ts/.kuzzlerc
  templates/app-scaffold/ts/.mocharc.json
  templates/app-scaffold/ts/README.md
  templates/app-scaffold/ts/app.ts
  templates/app-scaffold/ts/lib/.keep
  templates/app-scaffold/ts/package.json
  templates/app-scaffold/ts/tsconfig.json
  test/commands/app/scaffold.test.ts
  test/support.ts
Labels: changelog:bug-fixes

#74 Redis list keys
  README.md
  features/Redis.feature
  src/commands/redis/list-keys.ts
  src/support/kuzzle.ts
Labels: changelog:new-features
