Repository kuzzleio/kourou, pull requests merged in 2020-11, with the labels that each got.

#76 Add snapshots support
  .gitignore
  .travis.yml
  README.md
  features/Elasticsearch.feature
  features/docker/docker-compose.yml
  features/docker/elasticsearch/Dockerfile
  features/docker/elasticsearch/elasticsearch.yml
  features/run-kuzzle-stack.sh
  features/step_definitions/cli-steps.js
  src/commands/es/snapshot/create-repository.ts
  src/commands/es/snapshot/create.ts
  src/commands/es/snapshot/list.ts
  src/commands/es/snapshot/restore.ts
  src/common.ts
  src/support/kuzzle.ts
  tsconfig.json
Labels: changelog:new-features

#78 Fix app:scaffold and improve api action hook help
  README.md
  bin/run
  features/Sdk.feature
  package.json
  src/commands/app/scaffold.ts
  src/commands/sdk/execute.ts
  src/commands/sdk/query.ts
  src/hooks/command_not_found/api-action.ts
  src/support/kuzzle.ts
  templates/app-scaffold/ts/README.md
  templates/app-scaffold/ts/docker-compose.yml
  templates/app-scaffold/ts/package.json
  test/commands/app/scaffold.test.ts
  test/support.ts
Labels: changelog:enhancement

#80 Release 0.17.0
  .gitignore
  .travis.yml
  README.md
  bin/run
  features/Elasticsearch.feature
  features/Sdk.feature
  features/docker/docker-compose.yml
  features/docker/elasticsearch/Dockerfile
  features/docker/elasticsearch/elasticsearch.yml
  features/run-kuzzle-stack.sh
  features/step_definitions/cli-steps.js
  package-lock.json
  package.json
  src/commands/app/scaffold.ts
  src/commands/es/snapshot/create-repository.ts
  src/commands/es/snapshot/create.ts
  src/commands/es/snapshot/list.ts
  src/commands/es/snapshot/restore.ts
  src/commands/sdk/execute.ts
  src/commands/sdk/query.ts
  src/common.ts
  src/hooks/command_not_found/api-action.ts
  src/support/kuzzle.ts
  templates/app-scaffold/ts/README.md
  templates/app-scaffold/ts/docker-compose.yml
  templates/app-scaffold/ts/package.json
  test/commands/app/scaffold.test.ts
  test/support.ts
  tsconfig.json
Labels: release

#81 Add es:migrate command
  src/commands/es/migrate.ts
Labels: changelog:new-features

#86 Fix compatibility issues between app:scaffold and Typescript4
  .eslintrc
  .eslintrc.json
  .mocharc.json
  .nycrc
  README.md
  package-lock.json
  package.json
  src/commands/config/diff.ts
  src/commands/instance/kill.ts
  src/commands/instance/list.ts
  src/commands/instance/logs.ts
  src/common.ts
  src/support/dump-collection.ts
  src/support/editor.ts
  src/support/kuzzle.ts
  src/support/restore-collection.ts
  templates/app-scaffold/ts/package.json
  test/mocha.opts
  test/tsconfig.json
  tslint.json
Labels: changelog:bug-fixes

#87 Make sure that all dependencies for a scaffolded application are installed
  README.md
  package-lock.json
  package.json
  src/commands/app/scaffold.ts
  templates/app-scaffold/ts/README.md
  templates/app-scaffold/ts/package.json
Labels: changelog:bug-fixes

#82 Add an option to export data in a format compatible with Kuzzle fixtures
  README.md
  src/commands/collection/export.ts
  src/commands/index/export.ts
  src/support/dump-collection.ts
Labels: changelog:new-features
