Repository kuzzleio/kourou, pull requests merged in 2021-03, with the labels that each got.

#99 Add lang option support to document:search
  features/Document.feature
  src/commands/document/search.ts
Labels: changelog:enhancements

#100 Support SSL for ES commands
  features/Elasticsearch.feature
  src/commands/es/indices/cat.ts
  src/commands/es/indices/get.ts
  src/commands/es/indices/insert.ts
  src/commands/es/snapshot/create-repository.ts
  src/commands/es/snapshot/create.ts
  src/commands/es/snapshot/list.ts
  src/commands/es/snapshot/restore.ts
Labels: changelog:breaking-changes, changelog:enhancements

#101 Release 1.19.1
  README.md
  features/Document.feature
  features/Elasticsearch.feature
  package-lock.json
  package.json
  src/commands/document/search.ts
  src/commands/es/indices/cat.ts
  src/commands/es/indices/get.ts
  src/commands/es/indices/insert.ts
  src/commands/es/snapshot/create-repository.ts
  src/commands/es/snapshot/create.ts
  src/commands/es/snapshot/list.ts
  src/commands/es/snapshot/restore.ts
Labels: release
