Repository kuzzleio/kourou, pull requests merged in 2022-01, with the labels that each got.

#121 Release 0.19.5: fix plugin-help version
  .vscode/launch.json
  README.md
  features/.eslintrc.json
  features/CSV.feature
  features/Elasticsearch.feature
  features/docker/elasticsearch/elasticsearch.yml
  features/step_definitions/common/collection-steps.js
  features/step_definitions/common/file-steps.js
  package-lock.json
  package.json
  src/commands/collection/export.ts
  src/commands/es/snapshot/restore.ts
  src/common.ts
  src/support/dump-collection.ts
Labels: changelog:bug-fixes

#124 Print multiple error errors details
  src/common.ts
Labels: changelog:enhancements

#125 Scaffold: Check for KebabCase name and Ask for automatic conversion
  src/commands/app/scaffold.ts
Labels: changelog:enhancements

#126 Release 0.20.0
  README.md
  package-lock.json
  package.json
  src/commands/app/scaffold.ts
  src/commands/document/search.ts
  src/commands/role/export.ts
  src/common.ts
Labels: release

#127 Fix display of multiple errors
  README.md
  package-lock.json
  package.json
  src/common.ts
Labels: changelog:enhancements
