Repository kuzzleio/kourou, pull requests merged in 2022-06, with the labels that each got.

#141 Use new scaffold github repo
  .github/actions/build/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  README.md
  package-lock.json
  package.json
  scripts/postinstall.sh
  src/commands/app/scaffold.ts
  templates/app-scaffold/ts/.eslintignore
  templates/app-scaffold/ts/.eslintrc.json
  templates/app-scaffold/ts/.github/actions/backend-functional-test/action.yml
  templates/app-scaffold/ts/.github/actions/backend-lint/action.yml
  templates/app-scaffold/ts/.github/workflows/pull_request.workflow.yml
  templates/app-scaffold/ts/.github/workflows/push_master.workflow.yml
  templates/app-scaffold/ts/.github/workflows/push_production.workflow.yml
  templates/app-scaffold/ts/.gitignore
  templates/app-scaffold/ts/.mocharc.json
  templates/app-scaffold/ts/README.md
  templates/app-scaffold/ts/app.ts
  templates/app-scaffold/ts/docker-compose.yml
  templates/app-scaffold/ts/ergol.config.json
  templates/app-scaffold/ts/features/fixtures/fixtures.js
  templates/app-scaffold/ts/features/fixtures/mappings.js
  templates/app-scaffold/ts/features/fixtures/rights.js
  templates/app-scaffold/ts/features/step_definitions/common/auth-steps.js
  templates/app-scaffold/ts/features/step_definitions/common/collection-steps.js
  templates/app-scaffold/ts/features/step_definitions/common/controllers-steps.js
  templates/app-scaffold/ts/features/step_definitions/common/documents-steps.js
  templates/app-scaffold/ts/features/step_definitions/common/realtime-steps.js
  templates/app-scaffold/ts/features/step_definitions/common/security-steps.js
  templates/app-scaffold/ts/features/support/assertions.js
  templates/app-scaffold/ts/features/support/hooks.js
  templates/app-scaffold/ts/features/support/world.js
  templates/app-scaffold/ts/features/wait-kuzzle.sh
  templates/app-scaffold/ts/lib/.keep
  templates/app-scaffold/ts/lib/controllers/index.ts
  templates/app-scaffold/ts/lib/models/index.ts
  templates/app-scaffold/ts/lib/plugins/index.ts
  templates/app-scaffold/ts/lib/services/index.ts
  templates/app-scaffold/ts/lib/types/index.ts
  templates/app-scaffold/ts/package.json
  templates/app-scaffold/ts/tsconfig.json
  test/commands/app/scaffold.test.ts
Labels: changelog:enhancements

#144 Release 0.21.0
  .github/actions/build/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  README.md
  package-lock.json
  package.json
  scripts/postinstall.sh
  src/commands/app/scaffold.ts
  src/commands/app/start-services.ts
  src/commands/collection/export.ts
  src/commands/collection/import.ts
  src/commands/import.ts
  src/commands/index/export.ts
  src/commands/index/import.ts
  src/commands/instance/kill.ts
  src/commands/instance/spawn.ts
  src/commands/paas/init.ts
  src/commands/paas/login.ts
  src/commands/paas/publish.ts
  src/common.ts
  src/hooks/command_not_found/api-action.ts
  src/support/PaasKommand.ts
  src/support/kuzzle.ts
  templates/app-scaffold/ts/.eslintignore
  templates/app-scaffold/ts/.eslintrc.json
  templates/app-scaffold/ts/.github/actions/backend-functional-test/action.yml
  templates/app-scaffold/ts/.github/actions/backend-lint/action.yml
  templates/app-scaffold/ts/.github/workflows/pull_request.workflow.yml
  templates/app-scaffold/ts/.github/workflows/push_master.workflow.yml
  templates/app-scaffold/ts/.github/workflows/push_production.workflow.yml
  templates/app-scaffold/ts/.gitignore
  templates/app-scaffold/ts/.mocharc.json
  templates/app-scaffold/ts/README.md
  templates/app-scaffold/ts/app.ts
  templates/app-scaffold/ts/docker-compose.yml
  templates/app-scaffold/ts/ergol.config.json
  templates/app-scaffold/ts/features/fixtures/fixtures.js
  templates/app-scaffold/ts/features/fixtures/mappings.js
  templates/app-scaffold/ts/features/fixtures/rights.js
  templates/app-scaffold/ts/features/step_definitions/common/auth-steps.js
  templates/app-scaffold/ts/features/step_definitions/common/collection-steps.js
  templates/app-scaffold/ts/features/step_definitions/common/controllers-steps.js
  templates/app-scaffold/ts/features/step_definitions/common/documents-steps.js
  templates/app-scaffold/ts/features/step_definitions/common/realtime-steps.js
  templates/app-scaffold/ts/features/step_definitions/common/security-steps.js
  templates/app-scaffold/ts/features/support/assertions.js
  templates/app-scaffold/ts/features/support/hooks.js
  templates/app-scaffold/ts/features/support/world.js
  templates/app-scaffold/ts/features/wait-kuzzle.sh
  templates/app-scaffold/ts/lib/.keep
  templates/app-scaffold/ts/lib/controllers/index.ts
  templates/app-scaffold/ts/lib/models/index.ts
  templates/app-scaffold/ts/lib/plugins/index.ts
  templates/app-scaffold/ts/lib/services/index.ts
  templates/app-scaffold/ts/lib/types/index.ts
  templates/app-scaffold/ts/package.json
  templates/app-scaffold/ts/tsconfig.json
  test/commands/app/scaffold.test.ts
Labels: release

#138 Update PaaS commands
  .github/actions/build/action.yml
  .github/actions/es-lint/action.yml
  .github/actions/functional-test/action.yml
  package-lock.json
  package.json
  src/commands/paas/deploy.ts
  src/commands/paas/init.ts
  src/commands/paas/login.ts
  src/commands/paas/logs.ts
  src/common.ts
  src/support/PaasKommand.ts
Labels: changelog:new-features

#146 Release 0.23.0
  README.md
  package-lock.json
  package.json
  src/commands/app/debug-proxy.ts
Labels: release
