Repository kuzzleio/kourou, pull requests merged in 2023-01, with the labels that each got.

#171 Rework es:migrate to allow dump/restore using files
  features/Elasticsearch.feature
  features/step_definitions/cli-steps.js
  features/step_definitions/common/documents-steps.js
  features/support/world.js
  package-lock.json
  package.json
  src/commands/es/migrate.ts
  src/support/migrate/providers/elasticsearch.ts
  src/support/migrate/providers/file.ts
  src/support/migrate/providers/index.ts
  src/support/migrate/types.ts
Labels: changelog:new-features

#174 Release 0.25.0
  .eslintrc.json
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  README.md
  features/CSV.feature
  features/Collection.feature
  features/Elasticsearch.feature
  features/fixtures/mappings.js
  features/fixtures/migration.js
  features/step_definitions/cli-steps.js
  features/step_definitions/common/documents-steps.js
  features/support/world.js
  package-lock.json
  package.json
  src/commands/app/doctor.ts
  src/commands/app/scaffold.ts
  src/commands/collection/export.ts
  src/commands/collection/migrate.ts
  src/commands/document/search.ts
  src/commands/es/aliases/cat.ts
  src/commands/es/migrate.ts
  src/commands/index/export.ts
  src/commands/paas/login.ts
  src/commands/paas/logs.ts
  src/commands/sdk/query.ts
  src/commands/vault/encrypt.ts
  src/support/dump-collection.ts
  src/support/execute.ts
  src/support/kuzzle.ts
  src/support/migrate/providers/elasticsearch.ts
  src/support/migrate/providers/file.ts
  src/support/migrate/providers/index.ts
  src/support/migrate/types.ts
  src/support/restore-collection.ts
  test/commands/app/scaffold.test.ts
Labels: release

#175 fix: app:scaffold command description
  src/commands/app/scaffold.ts
Labels: changelog:enhancements, changelog:bug-fixes

#176 Support custom NPM registry hostname with `paas:login`
  src/commands/paas/login.ts
  src/support/PaasKommand.ts
Labels: changelog:enhancements

#178 Fix some issues when error occurs
  src/commands/paas/logs.ts
  src/support/kuzzle.ts
Labels: changelog:bug-fixes

#180 Release 0.25.1
  README.md
  package-lock.json
  package.json
  src/commands/app/scaffold.ts
  src/commands/paas/login.ts
  src/commands/paas/logs.ts
  src/support/PaasKommand.ts
  src/support/kuzzle.ts
Labels: release
