Repository kuzzleio/kourou, pull requests merged in 2024-01, with the labels that each got.

#188 Add command for dumping an Elasticsearch instance in the PaaS
  README.md
  package-lock.json
  package.json
  src/commands/paas/elasticsearch/dump.ts
Labels: changelog:new-features

#202 feat(paas): Update paas snapshot api call
  src/commands/paas/snapshots/restore.ts
Labels: changelog:enhancements

#203 Release 0.28.0
  README.md
  package-lock.json
  package.json
  src/commands/paas/elasticsearch/dump.ts
  src/commands/paas/snapshots/restore.ts
Labels: release
